name: glade_v2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


# IOS
#version: 2.0.0+4



#  201252
#Android
version: 2.0.12+56


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.0
  provider: ^4.0.0+1
#  flutter_ffmpeg: ^0.3.0
  http:
  flip_card: ^0.4.4
  intl: ^0.16.0
  email_validator: ^1.0.4
  hive: ^1.4.1+1ta
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  after_layout: ^1.0.7+2

  overlay_support: ^1.0.2
  shared_preferences: ^0.5.12
  flutter_masked_text: ^0.8.0
  webview_flutter: ^1.0.1
  camera: 0.7.0+2
  device_preview: ^0.5.5
  flushbar: ^1.10.4
  flutter_linkify: ^4.1.0
  url_launcher: ^5.7.10
  device_info: ^0.4.0+4
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.3.1+1
  package_info: ^0.4.3+2
  store_redirect: ^1.0.2
  get: ^3.26.0
  dio: ^3.0.10
  local_auth: ^0.6.2+3
  file_picker: ^2.1.7
  image_picker: ^0.6.7
  exif: ^1.0.3
  pdf: ^1.3.13
  percent_indicator: ^2.1.9
  printing: ^3.1.0
  permission_handler: ^4.2.0+hotfix.3
  flutter_keyboard_visibility: ^0.7.0
  flutter_boom_menu: ^1.0.2
  share: ^0.6.3+5
  pinput: ^1.0.0
  pin_code_fields:


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.2
  flutter_native_splash: ^0.3.2
  build_runner: ^1.7.2
  flutter_launcher_icons: 0.8.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  android: true
  ios: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"

#  "assets/images/glade.jpg"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/more/
    - assets/images/onboarding/
    - assets/images/add_a_business/
    - assets/images/states/
    - assets/images/crypto_currency/
    - assets/images/virtual_cards/
    - assets/images/receipt/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
